version: 2.1

executors:
  ubuntu-build:
    description: "A regular build executor based on ubuntu image"
    docker:
      - image: envoyproxy/envoy-build:ec38ecb88fd1abe55ab1daa2f6bd239ffccc9d98
    resource_class: xlarge
    working_directory: /source

jobs:
   release:
     executor: ubuntu-build
     environment:
       BAZEL_REMOTE_CACHE: https://storage.googleapis.com/envoy-circleci-bazel-cache/
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run:
           command:
             ci/do_circle_ci.sh bazel.release
           no_output_timeout: 60m
       - persist_to_workspace:
           root: .
           paths:
             - build_release
             - build_release_stripped
       - store_artifacts:
           path: /build/envoy/generated
           destination: /
   docker:
     docker:
       - image: docker
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - attach_workspace:
           at: .
       - setup_remote_docker
       - run: ci/docker_build.sh
       - run: ci/docker_push.sh
       - run: ci/docker_tag.sh
   asan:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - run: echo $CIRCLE_SHA1
       - run: echo $CIRCLE_PR_NUMBER
       - run: curl https://api.github.com/repos/envoyproxy/envoy/pulls/$CIRCLE_PR_NUMBER/commits
       - checkout
       - run: ci/do_circle_ci.sh bazel.asan
       - store_artifacts:
           path: /build/envoy/generated
           destination: /
   tsan:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.tsan
       - store_artifacts:
           path: /build/envoy/generated
           destination: /

   compile_time_options:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.compile_time_options
       - store_artifacts:
           path: /build/envoy/generated
           destination: /
   api:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh bazel.api
       - add_ssh_keys:
           fingerprints:
             - "fb:f3:fe:be:1c:b2:ec:b6:25:f9:7b:a6:87:54:02:8c"
       - run: ci/api_mirror.sh
       - store_artifacts:
           path: /build/envoy/generated
           destination: /
   filter_example_mirror:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - add_ssh_keys:
           fingerprints:
             - "f6:f9:df:90:9c:4b:5f:9c:f4:69:fd:42:94:ff:88:24"
       - run: ci/filter_example_mirror.sh
   ipv6_tests:
     machine: true
     steps:
     - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
     - checkout
     - run:
         name: enable ipv6
         command: |
           echo '{
             "ipv6": true,
             "fixed-cidr-v6": "2001:db8:1::/64"
           }' | sudo tee /etc/docker/daemon.json

           sudo service docker restart
     - run: dig go.googlesource.com A go.googlesource.com AAAA # Debug IPv6 network issues
     - run: ifconfig
     - run: route -A inet -A inet6
     - run: curl -v https://go.googlesource.com
     - run: curl -6 -v https://go.googlesource.com || true
     - run: ./ci/do_circle_ci_ipv6_tests.sh
     - store_artifacts:
         path: /tmp/envoy-docker/envoy/generated/failed-testlogs

   coverage:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run:
           command:
             ci/do_circle_ci.sh bazel.coverage
           no_output_timeout: 60m
       - run: ci/coverage_publish.sh
       - store_artifacts:
           path: /build/envoy/generated
           destination: /

   clang_tidy:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run:
           command:
             ci/do_circle_ci.sh bazel.clang_tidy
           no_output_timeout: 60m

   format:
     executor: ubuntu-build
     resource_class: small
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: pip install -r tools/requirements.txt
       - run: ci/do_circle_ci.sh check_format
       - run: ci/do_circle_ci.sh check_repositories
       - run: ci/do_circle_ci.sh check_spelling
       - run: ci/do_circle_ci.sh check_spelling_pedantic
   build_image:
     docker:
       - image: circleci/python:3.7
         environment:
           # See comment in do_circle_ci.sh for why we do this.
           NUM_CPUS: 8
     resource_class: xlarge
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - setup_remote_docker
       - run: ci/build_container/docker_push.sh
   docs:
     executor: ubuntu-build
     steps:
       - run: rm -rf /home/circleci/project/.git # CircleCI git caching is likely broken
       - checkout
       - run: ci/do_circle_ci.sh docs
       - add_ssh_keys:
           fingerprints:
             - "44:c7:a1:9e:f4:9e:a5:33:11:f1:0e:79:e1:55:c9:04"
       - run: docs/publish.sh
       - store_artifacts:
           path: generated/docs

workflows:
  version: 2
  all:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
      - docker:
          requires: [release]
          filters:
            tags:
              only: /^v.*/
      - asan
      - tsan
      - compile_time_options
      - api
      - filter_example_mirror
      - ipv6_tests
      - coverage
      - format
      - clang_tidy
      - build_image
      - docs:
          filters:
            tags:
              only: /^v.*/
