resources:
  containers:
  - container: envoy-build
    image: envoyproxy/envoy-build:ec38ecb88fd1abe55ab1daa2f6bd239ffccc9d98

jobs:
- job: BuildEnvoy
  timeoutInMinutes: 360
  pool:
    vmImage: 'Ubuntu 16.04'
  container: envoy-build
  steps:
  - script: bazel build //source/exe:envoy-static

