# Azure Pipelines
# TODO(lizan): Consider rolling all presubmit jobs into one file.
trigger:
- master

jobs:
- job: Windows
  timeoutInMinutes: 360
  pool:
    vmImage: "windows-latest"

  steps:
    - powershell: |
        .\ci\windows_ci_setup.ps1
        Write-Host "##vso[task.prependpath]$env:TOOLS_BIN_DIR"
      displayName: "Install dependencies"
      env:
        TOOLS_BIN_DIR: $(Pipeline.Workspace)\bin

    - bash: ci/windows_ci_steps.sh
      displayName: "Run Windows CI"
      env:
        TMPDIR: $(Agent.TempDirectory)
        BAZEL_VC: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC"
        BAZEL_SH: "C:\\Program Files\\Git\\bin\\bash.exe"
